import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children, //slot for children
  ads, //slot for ads
}: Readonly<{
  children: React.ReactNode;
  ads: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col justify-between min-h-screen">
          <Navbar />
          <div className="md:px-20 mt-28">{children}</div>
          <div className=" my-10 mx-auto flex justify-center">{ads}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
